"""implement strict multi tenant rbac

Revision ID: 3abde8eb3e8f
Revises: e5359e499bae
Create Date: 2026-06-07 16:32:14.820001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3abde8eb3e8f'
down_revision: Union[str, None] = 'e5359e499bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint('tasks_ibfk_3', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'workspace_id')
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'role')
    op.alter_column('workspace_invitations', 'role',
               existing_type=mysql.ENUM('owner', 'manager', 'member', 'viewer'),
               type_=sa.Enum('owner', 'admin', 'member', 'viewer', name='workspacememberrole'),
               existing_nullable=False)
    op.alter_column('workspace_members', 'role',
               existing_type=mysql.ENUM('owner', 'manager', 'member', 'viewer'),
               type_=sa.Enum('owner', 'admin', 'member', 'viewer', name='workspacememberrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'member'"))
    op.add_column('workspaces', sa.Column('billing_plan', sa.String(length=50), nullable=False))
    op.drop_constraint('workspaces_ibfk_2', 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('workspaces_ibfk_2', 'workspaces', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workspaces', 'billing_plan')
    op.alter_column('workspace_members', 'role',
               existing_type=sa.Enum('owner', 'admin', 'member', 'viewer', name='workspacememberrole'),
               type_=mysql.ENUM('owner', 'manager', 'member', 'viewer'),
               existing_nullable=False,
               existing_server_default=sa.text("'member'"))
    op.alter_column('workspace_invitations', 'role',
               existing_type=sa.Enum('owner', 'admin', 'member', 'viewer', name='workspacememberrole'),
               type_=mysql.ENUM('owner', 'manager', 'member', 'viewer'),
               existing_nullable=False)
    op.add_column('users', sa.Column('role', mysql.ENUM('user', 'super_admin'), server_default=sa.text("'user'"), nullable=False))
    op.drop_column('users', 'is_super_admin')
    op.add_column('tasks', sa.Column('workspace_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_ibfk_3', 'tasks', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'project_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'workspace_id')
    # ### end Alembic commands ###
